---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieterstockhausen.
--- DateTime: 12.01.22 18:01

mobdebugEnabled = false

if (mobdebugEnabled) then
    LrMobdebug = import 'LrMobdebug' -- Import LR/ZeroBrane debug module
    LrMobdebug.start()
end


function mobdebugOn()
    if (mobdebugEnabled) then
        LrMobdebug.on()
    end
end


