---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieterstockhausen.
--- DateTime: 12.01.22 18:01
--[[----------------------------------------------------------------------------
    For Mobdebug in general see:
        https://github.com/pkulchenko/MobDebug
    For the Lightroom Plugin see:
        http://notebook.kulchenko.com/zerobrane/debugging-lightroom-plugins-zerobrane-studio-ide
    For Mobdebug support in IntelliJ Idea you may use the EmmyLua plugin.
        https://plugins.jetbrains.com/plugin/9768-emmylua
-----------------------------------------------------------------------------]]

--[[----------------------------------------------------------------------------
    Enabling debugging
    set mobdebugEnabled = true
    import Debugger.lua in the module you want to debug:
        require ("Debugger")
    Add mobdebugOn() at the beginning of the functions you want to debug.
-----------------------------------------------------------------------------]]

mobdebugEnabled = false

if (mobdebugEnabled) then
    LrMobdebug = import 'LrMobdebug' -- Import LR/ZeroBrane debug module
    LrMobdebug.start()
end

function mobdebugOn()
    if (mobdebugEnabled) then
        LrMobdebug.on()
    end
end

function mobdebugOff()
    if (mobdebugEnabled) then
        LrMobdebug.off()
    end
end



