---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieter stockhausen.
--- DateTime: 04.05.21 22:00
---
-------------------------------------------------------------------------------

local LrApplication = import 'LrApplication'
local logger = require("Logger")

-------------------------------------------------------------------------------

local PureRawExportFilterProvider = {}

-------------------------------------------------------------------------------
function PureRawExportFilterProvider.shouldRenderPhoto(exportSettings, photo)
    logger.trace("start shouldRenderPhoto")

    -- if nothing was selected, nothing should be exported.
    local catalog = LrApplication.activeCatalog()
    local tp = catalog:getTargetPhoto()
    if ( tp == nil) then
        logger.trace("Nothing selected." )
        return false
    end

    -- only DNG and RAW are allowed
    local fileFormat = photo:getRawMetadata("fileFormat")
    if ( fileFormat == nil) thenc
      logger.trace("fileFormat is not set. So it seems not to be a DNG or RAW.")
      return false
    end
    logger.trace("Filetype for " .. photo:getFormattedMetadata("fileName") .. ": ".. fileFormat)
    if ( fileFormat ~= "DNG" and fileFormat ~= "RAW") then
        logger.trace("Photo is not a DNG or RAW. Skipped." )
        return false
    end

    -- skipp if already processed
    local software = photo:getFormattedMetadata('software')
    if ( software == nil) then
      logger.trace("Software is not set. So it was not processed by DxO PureRAW.")
      return true
    end
    logger.trace("Software: " .. software)
    shouldRender = software ~= "DxO PureRAW"
    return shouldRender
end

-------------------------------------------------------------------------------

function PureRawExportFilterProvider.sectionForFilterInDialog( f, propertyTable )
    return {
        title = LOC("$$$/LRPurePath/Filter/Title=Filter for valid photos"),
        f:row {
            spacing = f:control_spacing(),
            f:static_text {
                title = LOC("$$$/LRPureRaw/Filter/Descr=Only unprocessed RAW and DNG photos will pass."),
                fill_horizontal = 1,
            },
        }
    }
end

-------------------------------------------------------------------------------

return PureRawExportFilterProvider