---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dieterstockhausen.
--- DateTime: 04.05.21 22:00
---
local LrLogger = import("LrLogger")
local logger = LrLogger("PureRawLrLogger")
logger:enable("logfile")

local PureRawExportFilterProvider = {}
function PureRawExportFilterProvider.shouldRenderPhoto(exportSettings, photo)
    logger:trace("shouldRenderPhoto")
    local software = photo:getFormattedMetadata('software')
    logger:trace("Software: " .. software)
    shouldRender = software ~= "DxO PureRAW"
    return shouldRender
end
function PureRawExportFilterProvider.sectionForFilterInDialog( viewFactory, propertyTable )
    return {
        title = 'Creator External Tool Sample',
    }
end

return PureRawExportFilterProvider